[tasks.build]
description = "Build in debug"
run = "cargo build"

[tasks."build:release"]
description = "Build in release"
run = "cargo build --release"

[tasks.dev]
description = "Run in debug"
depends = ["clean"]
run = "cargo run"

[tasks."dev:tools"]
description = "Run in debug with devtools"
depends = ["clean"]
run = "cargo run --features devtools"

[tasks."start"]
description = "Run in release"
run = "cargo run --release"

[tasks.fmt]
description = "Format Rust code"
run = "cargo fmt --all"

[tasks.check]
description = "Check Rust code"
run = "cargo check"

[tasks.clean]
run = "rm -rf trace-*"
