[tasks.build]
description = "Build in debug"
run = "cargo build"

[tasks."build:release"]
description = "Build in release"
run = "cargo build --release"

[tasks.start]
description = "Run in debug (cleans trace-* first)"
shell = "powershell"
run = """
Get-ChildItem -Path . -Filter 'trace-*' -File -ErrorAction SilentlyContinue | Remove-Item -Force -ErrorAction SilentlyContinue
cargo run
"""

[tasks."start:devtools"]
description = "Run in debug with devtools (cleans trace-* first)"
shell = "powershell"
run = """
Get-ChildItem -Path . -Filter 'trace-*' -File -ErrorAction SilentlyContinue | Remove-Item -Force -ErrorAction SilentlyContinue
cargo run --features devtools
"""

[tasks."start:release"]
description = "Run in release (cleans trace-* first)"
shell = "powershell"
run = """
Get-ChildItem -Path . -Filter 'trace-*' -File -ErrorAction SilentlyContinue | Remove-Item -Force -ErrorAction SilentlyContinue
cargo run --release
"""

[tasks.fmt]
description = "Format Rust code"
run = "cargo fmt --all"

[tasks.check]
description = "Check Rust code"
run = "cargo check"
